name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 1 * *' # https://crontab.guru/
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts from old-websites
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in posts of old web-sites
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.joelonsoftware.com/feed/, https://ilya.grigorik.com/essays/rss/, https://johnnydecimal.com/rss.xml, https://ethical.net/feed/"
          comment_tag_name: "old-sub"
          feed_names: "Old Subs"
          max_post_count: 10
      - name: Pull in posts of Paul Grahm
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "http://www.aaronsw.com/2002/feeds/pgessays.rss"
          comment_tag_name: "paulgraham"
          disable_sort: true
          disable_item_validation: true
      - name: Addy Osmani Feeds
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCfetJpmQH2XpFj8uFgWsezw, https://addyosmani.com/feed.xml, https://addyo.substack.com/feed, https://dev.to/feed/addyosmani, https://news.google.com/rss/search?q=site:twitter.com/addyosmani&hl=en-US&gl=US&ceid=US:en"
          comment_tag_name: "addyo"
          max_post_count: 10
